root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "none"
  cmd = "make srv-install"
  full_bin = "scripts/srv/pm2.sh restart web"
  delay = 0
  exclude_dir = [ "server/web/frontend/node_modules", "test/", "integration-tests", "client", "play"]
  exclude_file = [ "server/web/static/js/foks.min.js" ]
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = [  ]
  include_ext = ["go", "templ", "ts", "css", "js" ]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
